### PR TITLE
Fix compatibility with mypy 0.990

### LINKED ISSUE #64: Mypy error: Type argument "X" of "DataclassSerializer" must be a subtype of "Dataclass"
When using code like:

```python
@dataclass
class MyDataclass:
    blah: int


class MySerializer(DataclassSerializer[MyDataclass]):
    ...
```

mypy version 0.990 will display a warning like:

> Type argument "MyDataclass" of "DataclassSerializer" must be a subtype of "Dataclass"

I am not yet sure whether this is a bug or intentional change, reported to mypy for clarification: https://github.com/python/mypy/issues/14029

### PR DESCRIPTION
**Pull request by intgr**
Fixes #64, as discussed at https://github.com/python/mypy/issues/14029

### CODE REVIEW

**Comment by oxan** [comment]
I was literally fixing this right now :joy:

I'll keep 27cd263223 if you don't mind, as it's identical except for the comment. Thanks anyway!

**Comment by intgr** [comment]
Haha no problem. Thanks!

**Comment by intgr** [comment]
I hope this fix can be released this week 🐶

**Comment by oxan** [comment]
Sure, I can put a release out this weekend.

**Comment by oxan** [comment]
@intgr I've just pushed v1.2.0 :)

**Comment by intgr** [comment]
Thanks!

**Pull request closed without merging**
