### PR TITLE
Type checking using mypy

### PR DESCRIPTION
**Pull request by oxan**
Make the package mypy clean and run type checking in CI.

### CODE REVIEW

**Comment by oxan** [comment]
Preferably, we could declare the DataclassSerializer like this, so that mypy knows what we're serializing:
```
class DataclassSerializer(rest_framework.serializers.Serializer[T]):
```

However, this breaks at runtime Python <3.9 because Serializer is not subscriptable, as `Serializer` is made a generic in stubs.

**Comment by intgr** [comment]
Thanks, I tried out these changes with my project and there are no new mypy errors.

> However, this breaks at runtime on Python <3.9 because Serializer is not subscriptable

Maybe it's possible to use a hack like:

```python
class DataclassSerializer(Serializer[T] if TYPE_CHECKING else Serializer):
    ...
```

Alternatively you could send a PR to django-rest-framework to add a `__class_getitem__` method. There is some precedent, Django itself has added the method to `QuerySet` and `Manager` classes.

**Comment by oxan** [comment]
> Thanks, I tried out these changes with my project and there are no new mypy errors.

Cool!

> Maybe it's possible to use a hack like:

Wow, that's disgusting, though I suppose it'd work. Let me consider it.

**Comment by oxan** [comment]
Actually, the issue with `Serializer[T]` turns out not to be Python 3.9-related, but instead it's DRF prior to 3.12 that doesn't have the `__class_getitem__` method on `Serializer` yet. 

However, I'm going to leave that improvement for the future, because getting rid of all usage of unspecialized generics turns out to be a bit more complicated: there's also `rest_framework.fields.Field` that _doesn't_ have `__class_getitem__` defined on it at all. That's only a problem because we define a type alias for it (which I really want to keep for readability reasons), which makes the subscript happen at runtime. Defining the type alias as a string (aside from being ugly) also confuses mypy if we don't add an explicit `TypeAlias` type for it, but that's only available on Python 3.10+. Sigh.

**Pull request merged**
