### PR TITLE
WIP: Allow serializer field configuration to be specified in metadata

### LINKED ISSUE #31: Allow specifying serializer field configuration using dataclass field metadata?
As @intgr mentioned in #30, it might be nice to support specifying the serializer field configuration using dataclass field metadata.

> I've thought about this a bit. It would be helpful and much cleaner if one could pass custom field kwargs overrides using dataclass `field(metadata=...)`, e.g.:
> 
> ```python
> @dataclass
> class Example:
>     string: str = field(metadata={"drf_field_args": {"allow_blank": True}})
>     lst: List[str] = field(metadata={"drf_field_args": {"child": serializers.CharField(allow_blank=True)}})
> ```
> 
> Does this seem like a mechanism you want to support @oxan?

> Or perhaps a metadata key that allows overriding the field as a whole
> 
> ```python
> @dataclass
> class Example:
>     string: str = field(metadata={"drf_field": serializers.CharField(allow_blank=True)})
>     lst: List[str] = field(metadata={
>         "drf_field": serializers.ListField(child=serializers.CharField(allow_blank=True))
>     })
> ```

### PR DESCRIPTION
**Pull request by oxan**
TODO:
- [ ] Consider whether supporting both approaches really is a good idea
- [ ] Consider metadata keys (I don't really like the current ones)
- [ ] Tests
- [ ] Documentation 

Closes #31

### CODE REVIEW

**Comment by jstasiak** [comment]
This is a big missing feature for me and it'd be great to have it – if there's anything I could do to help (like providing tests or documentation) please let me know.

**Comment by oxan** [comment]
Yeah, if you could provide tests and documentation that'd help. I'll see if I can find some time to finish, merge and release this later this week.

**Comment by oxan** [comment]
Though I suppose that's hard to do without the answer to the first two questions. Given that it's just two additional lines of code I've pretty much settled on supporting both approaches (as I can see situations were either is useful), and for now I'll keep the current names, though I may still decide switch it to `serializer_field` and `serializer_kwargs`.

**Comment by jstasiak** [comment]
I'm sorry I didn't help with this, after all, but I'm happy to see it resolved regardless. :)

**Comment by oxan** [comment]
No worries! Your comment was the motivation I needed to finally resolve this :)

**Pull request merged**
